app:
  host: localhost
  port: 10101
  secret: TMS-GIN

mysql:
  host: localhost
  port: 3306
  user: tms
  password: mysql
  table: tms_temp
  charset: utf8mb4
  parseTime: true
  loc: Local

  prefix: tb_
  singularTable: true

redis:
  host: localhost
  port: 6379
  password: 3y3IQezN
  db: 0

file:
  dir: /home/tms/Desktop/temp/TMS-GIN-FILE
  max_size: 10 #