app:
  host: localhost
  port: 10101
  secret: TMS-GIN

mysql:
  host: localhost
  port: 3306
  user: tms
  password: mysql
  table: im_db
  charset: utf8mb4
  parseTime: true
  loc: Local

  prefix: tb_
  singularTable: true

redis:
  host: localhost
  port: 6379
  password: redis
  db: 0

file:
  dir: /home/tms/workspace/temp/im-system
  max_size: 10 #